// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: session.sql

package repository

import (
	"context"

	"github.com/elzestia/fleet/pkg/models"
)

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM session
WHERE
    id = $1
    AND user_id = $2
`

func (q *Queries) DeleteSessionByID(ctx context.Context, arg models.DeleteSessionByIDParams) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, arg.ID, arg.UserID)
	return err
}

const getSessionByEntityId = `-- name: GetSessionByEntityId :one
SELECT
    id,
    user_id,
    expires_at,
    created_at,
    created_by,
    updated_at,
    updated_by,
    deleted_at,
    deleted_by
FROM session
WHERE
    id = $1
    AND user_id = $2
    AND expires_at > NOW()
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSessionByEntityId(ctx context.Context, arg models.GetSessionByEntityIdParams) (models.Session, error) {
	row := q.db.QueryRow(ctx, getSessionByEntityId, arg.ID, arg.UserID)
	var i models.Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO session (
    id,
    user_id,
    expires_at,
    created_by,
    updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

func (q *Queries) InsertSession(ctx context.Context, arg models.InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}
