// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy string             `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.Text        `json:"deleted_by"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy string             `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.Text        `json:"deleted_by"`
}

type User struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	EmailHash string             `json:"email_hash"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy string             `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.Text        `json:"deleted_by"`
}
