version: '2'
sql:
  - engine: 'postgresql'
    queries: '../db/queries'
    schema: '../db/schema.sql'
    gen:
      go:
        sql_package: "pgx/v5"
        package: 'repository'
        out: '../generated'
        emit_json_tags: true
        emit_prepared_queries: true
        emit_interface: true
        emit_exact_table_names: false
        emit_empty_slices: true
        emit_result_struct_pointers: false
        emit_params_struct_pointers: false
